<?php

namespace ContainerJVJ8bu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavBarService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\NavBar' autowired service.
     *
     * @return \App\Twig\Components\NavBar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/NavBar.php';

        $container->factories['service_container']['App\\Twig\\Components\\NavBar'] = function ($container) {
            $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

            if (isset($container->privates['App\\Twig\\Components\\NavBar'])) {
                return $container->privates['App\\Twig\\Components\\NavBar'];
            }

            return new \App\Twig\Components\NavBar($a);
        };

        return $container->factories['service_container']['App\\Twig\\Components\\NavBar']($container);
    }
}
