<?php

namespace ContainerJVJ8bu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingHandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Rating\RatingHandler' shared autowired service.
     *
     * @return \App\Rating\RatingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Rating/CalculateAverageRating.php';
        include_once \dirname(__DIR__, 4).'/src/Rating/CountRatingsPerValue.php';
        include_once \dirname(__DIR__, 4).'/src/Rating/RatingHandler.php';

        return $container->privates['App\\Rating\\RatingHandler'] = new \App\Rating\RatingHandler();
    }
}
