<?php

namespace ContainerJVJ8bu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameFixturesService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Doctrine\DataFixtures\VideoGameFixtures' shared autowired service.
     *
     * @return \App\Doctrine\DataFixtures\VideoGameFixtures
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Doctrine/DataFixtures/VideoGameFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/Rating/CalculateAverageRating.php';
        include_once \dirname(__DIR__, 4).'/src/Rating/CountRatingsPerValue.php';
        include_once \dirname(__DIR__, 4).'/src/Rating/RatingHandler.php';

        $a = ($container->privates['App\\Rating\\RatingHandler'] ??= new \App\Rating\RatingHandler());

        return $container->privates['App\\Doctrine\\DataFixtures\\VideoGameFixtures'] = new \App\Doctrine\DataFixtures\VideoGameFixtures(($container->privates['Faker\\Generator'] ?? $container->load('getGeneratorService')), $a, $a);
    }
}
