<?php

namespace ContainerSOiKB1L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qs9EjFcService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.qs9EjFc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'listFactory' => ['privates', 'App\\List\\ListFactory', 'getListFactoryService', true],
            'pagination' => ['privates', 'App\\List\\VideoGameList\\Pagination', NULL, 'Cannot autowire service "App\\List\\VideoGameList\\Pagination": argument "$page" of method "__construct()" is type-hinted "int", you should configure its value explicitly.'],
        ], [
            'listFactory' => 'App\\List\\ListFactory',
            'pagination' => 'App\\List\\VideoGameList\\Pagination',
        ]);

        if (isset($container->privates['.service_locator.qs9EjFc'])) {
            return $container->privates['.service_locator.qs9EjFc'];
        }

        return $container->privates['.service_locator.qs9EjFc'] = $instance;
    }
}
