<?php

namespace ContainerSOiKB1L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationValueResolver2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\List\VideoGameList\PaginationValueResolver' shared autowired service.
     *
     * @return \App\List\VideoGameList\PaginationValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/src/List/VideoGameList/PaginationValueResolver.php';

        return $container->privates['App\\List\\VideoGameList\\PaginationValueResolver'] = new \App\List\VideoGameList\PaginationValueResolver();
    }
}
