<?php

namespace ContainerSOiKB1L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTabsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Tabs' autowired service.
     *
     * @return \App\Twig\Components\Tabs
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Tabs.php';

        $container->factories['service_container']['App\\Twig\\Components\\Tabs'] = function ($container) {
            return new \App\Twig\Components\Tabs();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Tabs']($container);
    }
}
