<?php

namespace ContainerSOiKB1L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Doctrine\Repository\VideoGameRepository' shared autowired service.
     *
     * @return \App\Doctrine\Repository\VideoGameRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryProxy.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Doctrine/Repository/VideoGameRepository.php';

        return $container->privates['App\\Doctrine\\Repository\\VideoGameRepository'] = new \App\Doctrine\Repository\VideoGameRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
