security:
  enable_authenticator_manager: true

  password_hashers:
    App\Model\Entity\User:
      algorithm: auto

  providers:
    user_provider:
      entity:
        class: App\Model\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: user_provider

      custom_authenticators:
        - App\Security\LoginAuthenticator

      form_login: ~

      remember_me:
        secret: "%kernel.secret%"

      logout:
        path: auth_logout
        target: /

  access_control: []

when@test:
  security:
    password_hashers:
      App\Model\Entity\User:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
