<?php

namespace ContainerY0MD2xf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationValueResolverService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\List\VideoGameList\PaginationValueResolver' shared autowired service.
     *
     * @return \App\List\VideoGameList\PaginationValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\List\\VideoGameList\\PaginationValueResolver'] = new \App\List\VideoGameList\PaginationValueResolver();
    }
}
