<?php

namespace ContainerY0MD2xf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\ReviewType' shared autowired service.
     *
     * @return \App\Form\ReviewType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ReviewType'] = new \App\Form\ReviewType();
    }
}
