<?php

namespace ContainerY0MD2xf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameService extends App_KernelDevContainer
{
    /*
     * Gets the private '.errored..service_locator.8hT4VuS.App\Model\Entity\VideoGame' shared service.
     *
     * @return \App\Model\Entity\VideoGame
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8hT4VuS": it needs an instance of "App\\Model\\Entity\\VideoGame" but this type has been excluded in "config/services.yaml".');
    }
}
