<?php

namespace ContainerY0MD2xf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Doctrine\Repository\VideoGameRepository' shared autowired service.
     *
     * @return \App\Doctrine\Repository\VideoGameRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Doctrine\\Repository\\VideoGameRepository'] = new \App\Doctrine\Repository\VideoGameRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
