<?php

namespace ContainerMUDo61x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Rating' autowired service.
     *
     * @return \App\Twig\Components\Rating
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Rating.php';

        $container->factories['service_container']['App\\Twig\\Components\\Rating'] = function ($container) {
            return new \App\Twig\Components\Rating();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Rating']($container);
    }
}
