<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Model__Entity__VideoGame__CLASSMETADATA__' => 0,
'App__Model__Entity__NumberOfRatingPerValue__CLASSMETADATA__' => 1,
'App_Model_Entity_NumberOfRatingPerValue_$GEDMO_SLUGGABLE_CLASSMETADATA' => 2,
'App_Model_Entity_VideoGame_$GEDMO_SLUGGABLE_CLASSMETADATA' => 3,
'App__Model__Entity__Review__CLASSMETADATA__' => 4,
'App_Model_Entity_Review_$GEDMO_SLUGGABLE_CLASSMETADATA' => 2,
'App__Model__Entity__Tag__CLASSMETADATA__' => 5,
'App_Model_Entity_Tag_$GEDMO_SLUGGABLE_CLASSMETADATA' => 6,
'App__Model__Entity__User__CLASSMETADATA__' => 7,
'App_Model_Entity_User_$GEDMO_SLUGGABLE_CLASSMETADATA' => 2,
'Vich__UploaderBundle__Entity__File__CLASSMETADATA__' => 8,
'Vich_UploaderBundle_Entity_File_$GEDMO_SLUGGABLE_CLASSMETADATA' => 2,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\EmbeddedClassMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\EmbeddedClassMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToManyOwningSideMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinTableMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinTableMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Model\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Model\\Entity\\VideoGame',
                ],
                'embeddedClasses' => [
                    [
                        'numberOfRatingsPerValue' => $o[1],
                    ],
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[2],
                        'title' => $o[3],
                        'imageName' => $o[4],
                        'imageSize' => $o[5],
                        'slug' => $o[6],
                        'description' => $o[7],
                        'releaseDate' => $o[8],
                        'updatedAt' => $o[9],
                        'test' => $o[10],
                        'rating' => $o[11],
                        'averageRating' => $o[12],
                        'numberOfRatingsPerValue.numberOfOne' => $o[13],
                        'numberOfRatingsPerValue.numberOfTwo' => $o[14],
                        'numberOfRatingsPerValue.numberOfThree' => $o[15],
                        'numberOfRatingsPerValue.numberOfFour' => $o[16],
                        'numberOfRatingsPerValue.numberOfFive' => $o[17],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'image_name' => 'imageName',
                        'image_size' => 'imageSize',
                        'slug' => 'slug',
                        'description' => 'description',
                        'release_date' => 'releaseDate',
                        'updated_at' => 'updatedAt',
                        'test' => 'test',
                        'rating' => 'rating',
                        'average_rating' => 'averageRating',
                        'number_of_ratings_per_value_number_of_one' => 'numberOfRatingsPerValue.numberOfOne',
                        'number_of_ratings_per_value_number_of_two' => 'numberOfRatingsPerValue.numberOfTwo',
                        'number_of_ratings_per_value_number_of_three' => 'numberOfRatingsPerValue.numberOfThree',
                        'number_of_ratings_per_value_number_of_four' => 'numberOfRatingsPerValue.numberOfFour',
                        'number_of_ratings_per_value_number_of_five' => 'numberOfRatingsPerValue.numberOfFive',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'imageName' => 'image_name',
                        'imageSize' => 'image_size',
                        'slug' => 'slug',
                        'description' => 'description',
                        'releaseDate' => 'release_date',
                        'updatedAt' => 'updated_at',
                        'test' => 'test',
                        'rating' => 'rating',
                        'averageRating' => 'average_rating',
                        'numberOfRatingsPerValue.numberOfOne' => 'number_of_ratings_per_value_number_of_one',
                        'numberOfRatingsPerValue.numberOfTwo' => 'number_of_ratings_per_value_number_of_two',
                        'numberOfRatingsPerValue.numberOfThree' => 'number_of_ratings_per_value_number_of_three',
                        'numberOfRatingsPerValue.numberOfFour' => 'number_of_ratings_per_value_number_of_four',
                        'numberOfRatingsPerValue.numberOfFive' => 'number_of_ratings_per_value_number_of_five',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'video_game',
                    ],
                ],
                'associationMappings' => [
                    [
                        'tags' => $o[18],
                        'reviews' => $o[22],
                    ],
                ],
                'idGenerator' => [
                    $o[23],
                ],
                'name' => [
                    'App\\Model\\Entity\\VideoGame',
                    19 => 'video_game_tags',
                    'video_game_id',
                    'tag_id',
                ],
                'class' => [
                    1 => 'App\\Model\\Entity\\NumberOfRatingPerValue',
                ],
                'id' => [
                    2 => true,
                ],
                'type' => [
                    2 => 'integer',
                    'string',
                    'string',
                    'integer',
                    'string',
                    'text',
                    'date_immutable',
                    'datetime_immutable',
                    'text',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                ],
                'fieldName' => [
                    2 => 'id',
                    'title',
                    'imageName',
                    'imageSize',
                    'slug',
                    'description',
                    'releaseDate',
                    'updatedAt',
                    'test',
                    'rating',
                    'averageRating',
                    'numberOfRatingsPerValue.numberOfOne',
                    'numberOfRatingsPerValue.numberOfTwo',
                    'numberOfRatingsPerValue.numberOfThree',
                    'numberOfRatingsPerValue.numberOfFour',
                    'numberOfRatingsPerValue.numberOfFive',
                ],
                'columnName' => [
                    2 => 'id',
                    'title',
                    'image_name',
                    'image_size',
                    'slug',
                    'description',
                    'release_date',
                    'updated_at',
                    'test',
                    'rating',
                    'average_rating',
                    'number_of_ratings_per_value_number_of_one',
                    'number_of_ratings_per_value_number_of_two',
                    'number_of_ratings_per_value_number_of_three',
                    'number_of_ratings_per_value_number_of_four',
                    'number_of_ratings_per_value_number_of_five',
                ],
                'length' => [
                    3 => 100,
                ],
                'nullable' => [
                    4 => true,
                    true,
                    9 => true,
                    true,
                    true,
                    true,
                ],
                'unique' => [
                    6 => true,
                ],
                'originalClass' => [
                    13 => 'App\\Model\\Entity\\NumberOfRatingPerValue',
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                ],
                'originalField' => [
                    13 => 'numberOfOne',
                    'numberOfTwo',
                    'numberOfThree',
                    'numberOfFour',
                    'numberOfFive',
                ],
                'declaredField' => [
                    13 => 'numberOfRatingsPerValue',
                    'numberOfRatingsPerValue',
                    'numberOfRatingsPerValue',
                    'numberOfRatingsPerValue',
                    'numberOfRatingsPerValue',
                ],
                'fetch' => [
                    18 => 2,
                    22 => 2,
                ],
                'isOnDeleteCascade' => [
                    18 => true,
                ],
                'sourceEntity' => [
                    18 => 'App\\Model\\Entity\\VideoGame',
                    22 => 'App\\Model\\Entity\\VideoGame',
                ],
                'joinTable' => [
                    18 => $o[19],
                ],
                'joinTableColumns' => [
                    18 => [
                        'video_game_id',
                        'tag_id',
                    ],
                ],
                'relationToSourceKeyColumns' => [
                    18 => [
                        'video_game_id' => 'id',
                    ],
                ],
                'relationToTargetKeyColumns' => [
                    18 => [
                        'tag_id' => 'id',
                    ],
                ],
                'joinColumns' => [
                    19 => [
                        $o[20],
                    ],
                ],
                'inverseJoinColumns' => [
                    19 => [
                        $o[21],
                    ],
                ],
                'onDelete' => [
                    20 => 'CASCADE',
                    'CASCADE',
                ],
                'referencedColumnName' => [
                    20 => 'id',
                    'id',
                ],
                'mappedBy' => [
                    22 => 'videoGame',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    18 => 'tags',
                    22 => 'reviews',
                ],
                'targetEntity' => [
                    18 => 'App\\Model\\Entity\\Tag',
                    22 => 'App\\Model\\Entity\\Review',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Model\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                ],
                'isEmbeddedClass' => [
                    true,
                ],
                'fieldMappings' => [
                    [
                        'numberOfOne' => $o[1],
                        'numberOfTwo' => $o[2],
                        'numberOfThree' => $o[3],
                        'numberOfFour' => $o[4],
                        'numberOfFive' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'number_of_one' => 'numberOfOne',
                        'number_of_two' => 'numberOfTwo',
                        'number_of_three' => 'numberOfThree',
                        'number_of_four' => 'numberOfFour',
                        'number_of_five' => 'numberOfFive',
                    ],
                ],
                'columnNames' => [
                    [
                        'numberOfOne' => 'number_of_one',
                        'numberOfTwo' => 'number_of_two',
                        'numberOfThree' => 'number_of_three',
                        'numberOfFour' => 'number_of_four',
                        'numberOfFive' => 'number_of_five',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'number_of_rating_per_value',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'App\\Model\\Entity\\NumberOfRatingPerValue',
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'integer',
                    'integer',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'numberOfOne',
                    'numberOfTwo',
                    'numberOfThree',
                    'numberOfFour',
                    'numberOfFive',
                ],
                'columnName' => [
                    1 => 'number_of_one',
                    'number_of_two',
                    'number_of_three',
                    'number_of_four',
                    'number_of_five',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => [],
3 => [
    'slugs' => [
        'slug' => [
            'fields' => [
                'title',
            ],
            'slug' => 'slug',
            'style' => 'default',
            'dateFormat' => 'Y-m-d-H:i',
            'updatable' => true,
            'unique' => true,
            'unique_base' => null,
            'separator' => '-',
            'prefix' => '',
            'suffix' => '',
            'handlers' => [],
        ],
    ],
    'useObjectClass' => 'App\\Model\\Entity\\VideoGame',
],
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Model\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Model\\Entity\\Review',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'note' => $o[2],
                        'comment' => $o[3],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'note' => 'note',
                        'comment' => 'comment',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'note' => 'note',
                        'comment' => 'comment',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'review',
                    ],
                ],
                'associationMappings' => [
                    [
                        'videoGame' => $o[4],
                        'user' => $o[6],
                    ],
                ],
                'idGenerator' => [
                    $o[8],
                ],
                'name' => [
                    'App\\Model\\Entity\\Review',
                    5 => 'video_game_id',
                    7 => 'user_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'text',
                ],
                'fieldName' => [
                    1 => 'id',
                    'note',
                    'comment',
                ],
                'columnName' => [
                    1 => 'id',
                    'note',
                    'comment',
                ],
                'nullable' => [
                    3 => true,
                    5 => false,
                    7 => false,
                ],
                'fetch' => [
                    4 => 2,
                    6 => 2,
                ],
                'sourceEntity' => [
                    4 => 'App\\Model\\Entity\\Review',
                    6 => 'App\\Model\\Entity\\Review',
                ],
                'inversedBy' => [
                    4 => 'reviews',
                ],
                'sourceToTargetKeyColumns' => [
                    4 => [
                        'video_game_id' => 'id',
                    ],
                    6 => [
                        'user_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    4 => [
                        'id' => 'video_game_id',
                    ],
                    6 => [
                        'id' => 'user_id',
                    ],
                ],
                'joinColumns' => [
                    4 => [
                        $o[5],
                    ],
                    6 => [
                        $o[7],
                    ],
                ],
                'joinColumnFieldNames' => [
                    4 => [
                        'video_game_id' => 'video_game_id',
                    ],
                    6 => [
                        'user_id' => 'user_id',
                    ],
                ],
                'unique' => [
                    5 => false,
                    7 => false,
                ],
                'onDelete' => [
                    5 => 'CASCADE',
                ],
                'referencedColumnName' => [
                    5 => 'id',
                    7 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    4 => 'videoGame',
                    6 => 'user',
                ],
                'targetEntity' => [
                    4 => 'App\\Model\\Entity\\VideoGame',
                    6 => 'App\\Model\\Entity\\User',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Model\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Model\\Entity\\Tag',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'code' => $o[2],
                        'name' => $o[3],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'name' => 'name',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'code' => 'code',
                        'name' => 'name',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'tag',
                        'quoted' => true,
                    ],
                ],
                'idGenerator' => [
                    $o[4],
                ],
                'name' => [
                    'App\\Model\\Entity\\Tag',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'code',
                    'name',
                ],
                'columnName' => [
                    1 => 'id',
                    'code',
                    'name',
                ],
                'unique' => [
                    2 => true,
                ],
                'length' => [
                    3 => 30,
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => [
    'slugs' => [
        'code' => [
            'fields' => [
                'name',
            ],
            'slug' => 'code',
            'style' => 'default',
            'dateFormat' => 'Y-m-d-H:i',
            'updatable' => true,
            'unique' => true,
            'unique_base' => null,
            'separator' => '-',
            'prefix' => '',
            'suffix' => '',
            'handlers' => [],
        ],
    ],
    'useObjectClass' => 'App\\Model\\Entity\\Tag',
],
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Model\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Model\\Entity\\User',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'username' => $o[2],
                        'email' => $o[3],
                        'password' => $o[4],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'email' => 'email',
                        'password' => 'password',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'username' => 'username',
                        'email' => 'email',
                        'password' => 'password',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'user',
                        'quoted' => true,
                    ],
                ],
                'entityListeners' => [
                    [
                        'prePersist' => [
                            [
                                'class' => 'App\\Doctrine\\EntityListener\\UserListener',
                                'method' => 'hashPassword',
                            ],
                        ],
                    ],
                ],
                'idGenerator' => [
                    $o[5],
                ],
                'name' => [
                    'App\\Model\\Entity\\User',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'username',
                    'email',
                    'password',
                ],
                'columnName' => [
                    1 => 'id',
                    'username',
                    'email',
                    'password',
                ],
                'length' => [
                    2 => 30,
                    4 => 60,
                ],
                'unique' => [
                    2 => true,
                    true,
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Id\\AssignedGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\AssignedGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'Vich\\UploaderBundle\\Entity',
                ],
                'rootEntityName' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'isEmbeddedClass' => [
                    true,
                ],
                'fieldMappings' => [
                    [
                        'name' => $o[1],
                        'originalName' => $o[2],
                        'mimeType' => $o[3],
                        'size' => $o[4],
                        'dimensions' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'name' => 'name',
                        'original_name' => 'originalName',
                        'mime_type' => 'mimeType',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'columnNames' => [
                    [
                        'name' => 'name',
                        'originalName' => 'original_name',
                        'mimeType' => 'mime_type',
                        'size' => 'size',
                        'dimensions' => 'dimensions',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'file',
                    ],
                ],
                'idGenerator' => [
                    $o[6],
                ],
                'name' => [
                    'Vich\\UploaderBundle\\Entity\\File',
                ],
                'nullable' => [
                    1 => true,
                    true,
                    true,
                    true,
                    true,
                ],
                'type' => [
                    1 => 'string',
                    'string',
                    'string',
                    'integer',
                    'simple_array',
                ],
                'fieldName' => [
                    1 => 'name',
                    'originalName',
                    'mimeType',
                    'size',
                    'dimensions',
                ],
                'columnName' => [
                    1 => 'name',
                    'original_name',
                    'mime_type',
                    'size',
                    'dimensions',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
