<?php

namespace ContainerYPaw5sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8hT4VuSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8hT4VuS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'videoGame' => ['privates', '.errored..service_locator.8hT4VuS.App\\Model\\Entity\\VideoGame', NULL, 'Cannot autowire service ".service_locator.8hT4VuS": it needs an instance of "App\\Model\\Entity\\VideoGame" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'videoGame' => 'App\\Model\\Entity\\VideoGame',
        ]);

        if (isset($container->privates['.service_locator.8hT4VuS'])) {
            return $container->privates['.service_locator.8hT4VuS'];
        }

        return $container->privates['.service_locator.8hT4VuS'] = $instance;
    }
}
