<?php

namespace ContainerYPaw5sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Info' autowired service.
     *
     * @return \App\Twig\Components\Info
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Info.php';

        $container->factories['service_container']['App\\Twig\\Components\\Info'] = function ($container) {
            return new \App\Twig\Components\Info();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Info']($container);
    }
}
