<?php

namespace ContainerYPaw5sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNavBarService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\NavBar' autowired service.
     *
     * @return \App\Twig\Components\NavBar
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/NavBar.php';

        $container->factories['service_container']['App\\Twig\\Components\\NavBar'] = function ($container) {
            return new \App\Twig\Components\NavBar(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
        };

        return $container->factories['service_container']['App\\Twig\\Components\\NavBar']($container);
    }
}
