<?php

namespace ContainerYPaw5sO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Review' autowired service.
     *
     * @return \App\Twig\Components\Review
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Review.php';

        $container->factories['service_container']['App\\Twig\\Components\\Review'] = function ($container) {
            return new \App\Twig\Components\Review();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Review']($container);
    }
}
