<?php

namespace ContainerRCCFnOH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Doctrine\EntityListener\UserListener' shared autowired service.
     *
     * @return \App\Doctrine\EntityListener\UserListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Doctrine/EntityListener/UserListener.php';

        return $container->privates['App\\Doctrine\\EntityListener\\UserListener'] = new \App\Doctrine\EntityListener\UserListener(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
