<?php

namespace ContainerDjlWTSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'Faker\Generator' shared autowired service.
     *
     * @return \Faker\Generator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Generator.php';
        include_once \dirname(__DIR__, 4).'/src/Faker/FrenchGeneratorFactory.php';

        return $container->privates['Faker\\Generator'] = \App\Faker\FrenchGeneratorFactory::create();
    }
}
