<?php

namespace ContainerDjlWTSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgressService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Progress' autowired service.
     *
     * @return \App\Twig\Components\Progress
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Progress.php';

        $container->factories['service_container']['App\\Twig\\Components\\Progress'] = function ($container) {
            return new \App\Twig\Components\Progress();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Progress']($container);
    }
}
