<?php

namespace ContainerDjlWTSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameVoter2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Security\Voter\VideoGameVoter' shared autowired service.
     *
     * @return \App\Security\Voter\VideoGameVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/src/Security/Voter/VideoGameVoter.php';

        return $container->privates['App\\Security\\Voter\\VideoGameVoter'] = new \App\Security\Voter\VideoGameVoter();
    }
}
