<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_Fixtures_LoaderService extends App_KernelTestContainer
{
    /*
     * Gets the private 'doctrine.fixtures.loader' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine.fixtures.loader'] = $instance = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $instance->addFixtures([['fixture' => ($container->privates['App\\Doctrine\\DataFixtures\\TagFixtures'] ??= new \App\Doctrine\DataFixtures\TagFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\Doctrine\\DataFixtures\\UserFixtures'] ??= new \App\Doctrine\DataFixtures\UserFixtures()), 'groups' => []], ['fixture' => ($container->privates['App\\Doctrine\\DataFixtures\\VideoGameFixtures'] ?? $container->load('getVideoGameFixturesService')), 'groups' => []]]);

        return $instance;
    }
}
