<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterTypeService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Form\FilterType' shared autowired service.
     *
     * @return \App\Form\FilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FilterType'] = new \App\Form\FilterType();
    }
}
