<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGedmo_Listener_SluggableService extends App_KernelTestContainer
{
    /*
     * Gets the private 'gedmo.listener.sluggable' shared autowired service.
     *
     * @return \Gedmo\Sluggable\SluggableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['gedmo.listener.sluggable'] = new \Gedmo\Sluggable\SluggableListener();
    }
}
