<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneratorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'Faker\Generator' shared autowired service.
     *
     * @return \Faker\Generator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Faker\\Generator'] = \App\Faker\FrenchGeneratorFactory::create();
    }
}
