<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagination2Service extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Twig\Components\Pagination' autowired service.
     *
     * @return \App\Twig\Components\Pagination
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->factories['service_container']['App\\Twig\\Components\\Pagination'] = function ($container) {
            return new \App\Twig\Components\Pagination();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Pagination']($container);
    }
}
