<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingHandlerService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Rating\RatingHandler' shared autowired service.
     *
     * @return \App\Rating\RatingHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Rating\\RatingHandler'] = new \App\Rating\RatingHandler();
    }
}
