<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserFixturesService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Doctrine\DataFixtures\UserFixtures' shared autowired service.
     *
     * @return \App\Doctrine\DataFixtures\UserFixtures
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Doctrine\\DataFixtures\\UserFixtures'] = new \App\Doctrine\DataFixtures\UserFixtures();
    }
}
