<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameVoterService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Security\Voter\VideoGameVoter' shared autowired service.
     *
     * @return \App\Security\Voter\VideoGameVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\Voter\\VideoGameVoter'] = new \App\Security\Voter\VideoGameVoter();
    }
}
