<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoGameFixturesService extends App_KernelTestContainer
{
    /*
     * Gets the private 'App\Doctrine\DataFixtures\VideoGameFixtures' shared autowired service.
     *
     * @return \App\Doctrine\DataFixtures\VideoGameFixtures
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Rating\\RatingHandler'] ??= new \App\Rating\RatingHandler());

        return $container->privates['App\\Doctrine\\DataFixtures\\VideoGameFixtures'] = new \App\Doctrine\DataFixtures\VideoGameFixtures(($container->privates['Faker\\Generator'] ?? $container->load('getGeneratorService')), $a, $a);
    }
}
