<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_FileInjectorService extends App_KernelTestContainer
{
    /*
     * Gets the private 'vich_uploader.file_injector' shared service.
     *
     * @return \Vich\UploaderBundle\Injector\FileInjector
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['vich_uploader.file_injector'] = new \Vich\UploaderBundle\Injector\FileInjector(($container->privates['vich_uploader.storage.file_system'] ?? $container->load('getVichUploader_Storage_FileSystemService')));
    }
}
