<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_PropertyMappingResolverService extends App_KernelTestContainer
{
    /*
     * Gets the private 'vich_uploader.property_mapping_resolver' shared service.
     *
     * @return \Vich\UploaderBundle\Mapping\PropertyMappingResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['vich_uploader.property_mapping_resolver'] = new \Vich\UploaderBundle\Mapping\PropertyMappingResolver($container, $container->parameters['vich_uploader.mappings'], '_name');
    }
}
