<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_Listener_Clean_VideoGamesService extends App_KernelTestContainer
{
    /*
     * Gets the private 'vich_uploader.listener.clean.video_games' shared service.
     *
     * @return \Vich\UploaderBundle\EventListener\Doctrine\CleanListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['vich_uploader.upload_handler'] ?? $container->load('getVichUploader_UploadHandlerService'));

        if (isset($container->privates['vich_uploader.listener.clean.video_games'])) {
            return $container->privates['vich_uploader.listener.clean.video_games'];
        }

        return $container->privates['vich_uploader.listener.clean.video_games'] = new \Vich\UploaderBundle\EventListener\Doctrine\CleanListener('video_games', ($container->privates['vich_uploader.adapter.orm'] ??= new \Vich\UploaderBundle\Adapter\ORM\DoctrineORMAdapter()), ($container->privates['vich_uploader.metadata_reader'] ?? self::getVichUploader_MetadataReaderService($container)), $a);
    }
}
