<?php

namespace ContainerZ00VAJy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVichUploader_Adapter_OrmService extends App_KernelTestContainer
{
    /*
     * Gets the private 'vich_uploader.adapter.orm' shared service.
     *
     * @return \Vich\UploaderBundle\Adapter\ORM\DoctrineORMAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['vich_uploader.adapter.orm'] = new \Vich\UploaderBundle\Adapter\ORM\DoctrineORMAdapter();
    }
}
