<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC75uaHg\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC75uaHg/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerC75uaHg.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerC75uaHg\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerC75uaHg\App_KernelTestDebugContainer([
    'container.build_hash' => 'C75uaHg',
    'container.build_id' => '5f2236ce',
    'container.build_time' => 1790412447,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC75uaHg');
