<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEgYjUDJ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEgYjUDJ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEgYjUDJ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEgYjUDJ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerEgYjUDJ\App_KernelTestDebugContainer([
    'container.build_hash' => 'EgYjUDJ',
    'container.build_id' => 'e911cdec',
    'container.build_time' => 1790587404,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEgYjUDJ');
