<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ00VAJy\App_KernelTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ00VAJy/App_KernelTestContainer.php') {
    touch(__DIR__.'/ContainerZ00VAJy.legacy');

    return;
}

if (!\class_exists(App_KernelTestContainer::class, false)) {
    \class_alias(\ContainerZ00VAJy\App_KernelTestContainer::class, App_KernelTestContainer::class, false);
}

return new \ContainerZ00VAJy\App_KernelTestContainer([
    'container.build_hash' => 'Z00VAJy',
    'container.build_id' => '80e67d5b',
    'container.build_time' => 1779304786,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ00VAJy');
