<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSOiKB1L\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSOiKB1L/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSOiKB1L.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSOiKB1L\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerSOiKB1L\App_KernelTestDebugContainer([
    'container.build_hash' => 'SOiKB1L',
    'container.build_id' => 'ae56743f',
    'container.build_time' => 1782200237,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSOiKB1L');
