<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDjlWTSS\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDjlWTSS/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDjlWTSS.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDjlWTSS\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDjlWTSS\App_KernelTestDebugContainer([
    'container.build_hash' => 'DjlWTSS',
    'container.build_id' => '8920454c',
    'container.build_time' => 1779304793,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDjlWTSS');
