<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_logout_main' => [[], [], [], [['text', '/auth/logout']], [], [], []],
    'auth_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/auth/login']], [], [], []],
    'auth_register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/auth/register']], [], [], []],
    'video_games_list' => [[], ['_controller' => 'App\\Controller\\VideoGameController::list'], [], [['text', '/']], [], [], []],
    'video_games_show' => [['slug'], ['_controller' => 'App\\Controller\\VideoGameController::show'], [], [['variable', '/', '[^/]++', 'slug', true]], [], [], []],
    'App\Controller\AuthController::login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/auth/login']], [], [], []],
    'App\Controller\AuthController::register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/auth/register']], [], [], []],
    'App\Controller\VideoGameController::list' => [[], ['_controller' => 'App\\Controller\\VideoGameController::list'], [], [['text', '/']], [], [], []],
    'App\Controller\VideoGameController::show' => [['slug'], ['_controller' => 'App\\Controller\\VideoGameController::show'], [], [['variable', '/', '[^/]++', 'slug', true]], [], [], []],
];
