<?php

namespace ContainerJ2dugve;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGedmo_Listener_SluggableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gedmo.listener.sluggable' shared autowired service.
     *
     * @return \Gedmo\Sluggable\SluggableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/src/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Mapping/MappedEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Sluggable/SluggableListener.php';

        return $container->privates['gedmo.listener.sluggable'] = new \Gedmo\Sluggable\SluggableListener();
    }
}
