<?php

namespace ContainerJ2dugve;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginAuthenticatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\LoginAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Authenticator/AbstractAuthenticator.php';
        include_once \dirname(__DIR__, 4).'/src/Security/LoginAuthenticator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\LoginAuthenticator'])) {
            return $container->privates['App\\Security\\LoginAuthenticator'];
        }
        $b = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['App\\Security\\LoginAuthenticator'])) {
            return $container->privates['App\\Security\\LoginAuthenticator'];
        }

        $instance = new \App\Security\LoginAuthenticator(($container->services['router'] ?? self::getRouterService($container)), $a, $b);

        if (isset($container->privates['App\\Security\\LoginAuthenticator'])) {
            return $container->privates['App\\Security\\LoginAuthenticator'];
        }

        return $container->privates['App\\Security\\LoginAuthenticator'] = $instance;
    }
}
