<?php

namespace ContainerJ2dugve;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaginationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\List\VideoGameList\Pagination' shared autowired service.
     *
     * @return \App\List\VideoGameList\Pagination
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\List\\VideoGameList\\Pagination": argument "$page" of method "__construct()" is type-hinted "int", you should configure its value explicitly.');
    }
}
