<?php

namespace ContainerJ2dugve;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentPropertiesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_properties' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentProperties
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentProperties.php';

        return $container->privates['ux.twig_component.component_properties'] = new \Symfony\UX\TwigComponent\ComponentProperties(($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), ['App\\Twig\\Components\\Alert' => NULL, 'App\\Twig\\Components\\Card' => NULL, 'App\\Twig\\Components\\Filter' => NULL, 'App\\Twig\\Components\\Info' => NULL, 'App\\Twig\\Components\\NavBar' => NULL, 'App\\Twig\\Components\\Pagination' => NULL, 'App\\Twig\\Components\\Progress' => NULL, 'App\\Twig\\Components\\Rating' => NULL, 'App\\Twig\\Components\\Review' => NULL, 'App\\Twig\\Components\\Sorting' => NULL, 'App\\Twig\\Components\\Tabs' => NULL], ($container->privates['cache.ux.twig_component'] ?? self::getCache_Ux_TwigComponentService($container)));
    }
}
