<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYPaw5sO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYPaw5sO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYPaw5sO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYPaw5sO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYPaw5sO\App_KernelDevDebugContainer([
    'container.build_hash' => 'YPaw5sO',
    'container.build_id' => '8d3c54a5',
    'container.build_time' => 1782490033,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYPaw5sO');
