<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2dugve\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2dugve/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2dugve.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2dugve\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2dugve\App_KernelDevDebugContainer([
    'container.build_hash' => 'J2dugve',
    'container.build_id' => '6cd213c2',
    'container.build_time' => 1782825394,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2dugve');
