<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY0MD2xf\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY0MD2xf/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerY0MD2xf.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerY0MD2xf\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerY0MD2xf\App_KernelDevContainer([
    'container.build_hash' => 'Y0MD2xf',
    'container.build_id' => '11a853dd',
    'container.build_time' => 1779305768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY0MD2xf');
