<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUDo61x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUDo61x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMUDo61x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMUDo61x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMUDo61x\App_KernelDevDebugContainer([
    'container.build_hash' => 'MUDo61x',
    'container.build_id' => '2e710deb',
    'container.build_time' => 1779354013,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUDo61x');
