<?php

namespace ContainerW44Tj6V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Card' autowired service.
     *
     * @return \App\Twig\Components\Card
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Card.php';

        $container->factories['service_container']['App\\Twig\\Components\\Card'] = function ($container) {
            return new \App\Twig\Components\Card();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Card']($container);
    }
}
