<?php

namespace ContainerW44Tj6V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Twig\Components\Filter' autowired service.
     *
     * @return \App\Twig\Components\Filter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/Filter.php';

        $container->factories['service_container']['App\\Twig\\Components\\Filter'] = function ($container) {
            return new \App\Twig\Components\Filter();
        };

        return $container->factories['service_container']['App\\Twig\\Components\\Filter']($container);
    }
}
