<?php

namespace ContainerW44Tj6V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\List\ListFactory' shared autowired service.
     *
     * @return \App\List\ListFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/List/ListFactory.php';

        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->privates['App\\List\\ListFactory'])) {
            return $container->privates['App\\List\\ListFactory'];
        }

        return $container->privates['App\\List\\ListFactory'] = new \App\List\ListFactory(($container->services['router'] ?? self::getRouterService($container)), $a, ($container->privates['App\\Doctrine\\Repository\\VideoGameRepository'] ?? $container->load('getVideoGameRepositoryService')));
    }
}
